substitutions:
  _REGION: asia-south1
  _SERVICE_NAME: looker-studio-pdf-api
  _MEMORY: 4Gi
  _CPU: "2"
  _TIMEOUT: "900"
  _CONCURRENCY: "1"
  _PORT: "8080"
  _STORAGE_ACCOUNT_NAME: "nczdocsstaging"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - ${_MEMORY}
      - --cpu
      - ${_CPU}
      - --timeout
      - ${_TIMEOUT}
      - --concurrency
      - ${_CONCURRENCY}
      - --port
      - ${_PORT}
      - --cpu-boost
      - --update-env-vars
      - LOOKER_PUPPETEER_HEADLESS=true,LOOKER_PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium,DB_HOST=ncz.database.windows.net,DB_DATABASE=nczdev,STORAGE_ACCOUNT_NAME=${_STORAGE_ACCOUNT_NAME}
      - --update-secrets
      - DB_USERNAME=DB_USERNAME:latest,DB_PASSWORD=DB_PASSWORD:latest,FIREBASE_SERVICE_ACCOUNT_JSON=FIREBASE_SERVICE_ACCOUNT_JSON:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STORAGE_ACCOUNT_KEY=STORAGE_ACCOUNT_KEY:latest

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
